POST http://localhost:7071/api/UrlCreate
Content-Type: application/json

{
    // [Required] The url you wish to have a short version for
    "url": "https://docs.microsoft.com/en-ca/azure/azure-functions/functions-create-your-first-function-visual-studio",
    
    // [Optional] Title of the page, or text description of your choice.
    "title": "Quickstart: Create your first function in Azure using Visual Studio",

    // [Optional] the end of the URL. If nothing one will be generated for you.
    "vanity": "azFunc"
}